### ISSUE TITLE
StackOverflowException when exporting XLIFF and there is a link inside a list item pointing to itself

### ISSUE THREAD

**Issue by sorincarbunaru** [rmraya/OpenXLIFF#30]
Actually inside the list item there are 2 paragraphs, and at some point in the second paragraph there is a cross reference pointing to the first one. I attached a minimal sample: [testFluenta.zip](https://github.com/rmraya/OpenXLIFF/files/14433332/testFluenta.zip).

The error is the following:
````
Exception in thread "Thread-35" java.lang.StackOverflowError
        at java.base/java.lang.RuntimeException.<init>(RuntimeException.java:52)
        at java.base/java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:40)
        at java.base/java.util.regex.PatternSyntaxException.<init>(PatternSyntaxException.java:58)
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1432)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
        at java.base/java.lang.String.split(String.java:3155)
        at java.base/java.lang.String.split(String.java:3201)
        at com.maxprograms.converters.ditamap.DitaParser.ditaClass(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
        at com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
````

**Comment by rmraya** [comment]
Cannot reproduce. Works fine for me.

**Comment by rmraya** [comment]
[TestMap.ditamap.xlf.zip](https://github.com/rmraya/OpenXLIFF/files/14433530/TestMap.ditamap.xlf.zip)
