### ISSUE TITLE
SAXException when converting docx file

### ISSUE THREAD

**Issue by foolo** [rmraya/OpenXLIFF#6]
For certain file with lots of tags, an exception occurs on converting:

Steps:
./convert.sh -file notice.docx -srcLang en -tgtLang sv -2.0
(file is attached)

Output:
```
Oct 24, 2019 11:45:17 AM com.maxprograms.xml.CustomErrorHandler fatalError
SEVERE: 1:250 Element type "p" must be followed by either attribute specifications, ">" or "/>".
Oct 24, 2019 11:45:17 AM com.maxprograms.converters.msoffice.MSOffice2Xliff run
SEVERE: Error converting MS Office file
org.xml.sax.SAXException: [Fatal Error] 1:250 Element type "p" must be followed by either attribute specifications, ">" or "/>".
	at openxliff/com.maxprograms.xml.CustomErrorHandler.fatalError(CustomErrorHandler.java:43)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:181)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.seekCloseOfStartTag(XMLDocumentFragmentScannerImpl.java:1433)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:242)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at openxliff/com.maxprograms.xml.SAXBuilder.build(SAXBuilder.java:89)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.writeSegment(MSOffice2Xliff.java:141)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePara(MSOffice2Xliff.java:386)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:587)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePhrase(MSOffice2Xliff.java:589)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recursePara(MSOffice2Xliff.java:419)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recurse(MSOffice2Xliff.java:283)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.recurse(MSOffice2Xliff.java:285)
	at openxliff/com.maxprograms.converters.msoffice.MSOffice2Xliff.run(MSOffice2Xliff.java:97)
	at openxliff/com.maxprograms.converters.office.Office2Xliff.run(Office2Xliff.java:131)
	at openxliff/com.maxprograms.converters.Convert.run(Convert.java:366)
	at openxliff/com.maxprograms.converters.Convert.main(Convert.java:238)

```

[notice.docx](https://github.com/rmraya/OpenXLIFF/files/3766902/notice.docx)

**Comment by rmraya** [comment]
You should clean the file with CodeZapper or similar before attempting to convert. A file with too many tags is untranslatable.

**Comment by foolo** [comment]
Is there any way for the user to know whether the file needs to be cleaned? At least it would be good with an error message, warning message, or some way to programmatically detect it, instead of just a crash. I don't want to put the technical responsibility on the end-user.

Another note is that it does not seem that all tags in ```tags``` variable become actual tags in the xliff file. I tried with some different docx file and in one example the maximum size of ```tags``` was 70 or something, but there were no segment created with that many 70 tags. The segments still looked OK. So i don't think that too many tags necessarily make the file "untranslatable". In the case with "notice.docx", it's only some junk data that does not contain any actual text, so it will all be hidden in the end.

**Comment by rmraya** [comment]
Professional translators know when a file needs to be cleaned before translation. It is their job.

You can detect the crash and let the user know that the file needs pre-processing.

Segmentation generates tags. The filter removes unnecessary tags or merges adjacent tags later during processing. The Office filter does a good job post-processing tags.

**Comment by foolo** [comment]
Ok :) So it depends a bit on what we assume about the user.

But anyway, here's a concrete suggestion:
Maybe you saw in the other thread my comment about the size of the UTF private use area, E000 to F8FF  (which is used by ```tags``` for mapping the tags).
Since the private use area area is only 6400 code points, we cannot store more than 6400 tags in ```tags```.
So we could add a check In ```Segmenter.segment(String string) {```
after ```String pureText = prepareString(string);```

If we add a check something like this:
```
if (tags.size() > 6400) {
   // throw an exception "document has too many tags, needs pre-processing"
}
```
then we would get this error message instead of SAXException above, and also we would not need to wait the 20-minutes before the error.

**Comment by rmraya** [comment]
That extra check will slow processing. Not a good idea.

**Comment by foolo** [comment]
It is only one if-statement which will only run once every call to ```Segmenter.segment(String string)```.
(I tried with a 4000-word document and it was called 320 times). This if-statement should take less than a microsecond, so the time penalty should be less than a millisecond even for a huge document.

I will paste the code in its context, for clarity

```
public String[] segment(String string) {
	if (string == null || string.equals("")) {
		return new String[] {};
	}
	String pureText = prepareString(string);

	// here's my addition             
	if (tags.size() > 6400) {
		// throw an exception "document has too many tags, needs pre-processing"
	}
(...)
```

**Comment by rmraya** [comment]
Still a bad idea. It would mask the real cause of the problem.

The stack trace you posted does not mention any issue with extended characters. The tags Hashtable<> uses String for key, not a character.

**Comment by rmraya** [comment]
Crossing character ranges does not happen in real life. This code has been in actual use for 10 years by thousands of translators, most of them working with CJK languages, and that kind of error was never reported.

**Comment by foolo** [comment]
Ok. That's good to hear. Btw, you mentioned CodeZapper or similar. CodeZapper seems to be a windows-only application, right? Do you know any other similar software?

**Comment by rmraya** [comment]
Check http://translatortools.net/about.html

**Comment by rmraya** [comment]
Translator that work in macOS use Microsoft Word to clean their files.
